sudo: required
language: ruby

before_install: gem install bundler -v 1.17.1
script: gem build rubx-mixin.gemspec

rvm:
  - 2.6.0-preview2
  - 2.5.3
  - 2.4.5
  - 2.3.8

deploy:
  provider: rubygems
  api_key:
    secure: "nVO4OFFFL+Zxdar/LKYRYft6ZlbHvBnTreqTGUxb6dq7bJuD4LRgzuDNefG/VV3XlqUHvcqwsnuuXPerQDlH9zhfUt2kz20h3b4xUSNYT6p+3/IF/U5z1D/yHiHirzWG57ehFaovwvGHFRY6R6XQ6YCz3t785THAbL9uu7jlbzI67yqcd1KFbrk5CkHXCyZl3E7tv/LPm+ZV3zHD4XiCZgOqx2GJ8QDYUq0+FjvbgqI6jvr7R+eIhLgmeHSuu1FOUWrWc7rMhhclTXZnci8Uf/UZ7XitvER2EzRT89ScFsgmmaAS61wOvqJ1+Ahc1nGNm21cThhtTSGIJW3vXxlRJ8ksablcRd2HqAQhwaOCQn6qMVpiDz8dlQ34Y+2TvoWVdqyeWsCczvM/mYH/RctbuA4RPVBxFGrl1U7zp35s0fotGoO4JvRB0hqBav9b/Ah5BtoXxhkZFGRV9IEzF+IaCVGNZiu+bFinw0L5sAsW+/9LHSV1hSXnyVUwsvw32xTIAMB+b+MLjkfZZQd7opAcGH0jZiNbwBlfgnFbnwCPHDkafdNlX+vNlrj7qEM9bmPBlG8uWRQhgsdgrvS2mkpNxzd91TqW4TK9CSkgCZevutO+GwgvvPw99F2Pi9V8ydwf80PtI8Z4K46Vt0kzkYFVxK40P1ZXcRV4A2i8UmVlKys="
  on:
    rvm: 2.5.3
    tags: true
  gem: rubx-mixin
  gemspec: rubx-mixin.gemspec

notfications:
  email: false